services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    working_dir: /var/www

  db:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "4000:3306"  # локально на 4000, внутри контейнера 3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

